name: GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "doc/website/**"
      - "website/homepage/**"
      - ".github/workflows/gh-pages.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      - name: Setup bazel
        uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Build
        run: |
          bazel build //website/homepage:homepage_tgz
          tar xvf bazel-bin/website/homepage/homepage.tgz

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: ziyixi/ziyixi.github.io
          publish_branch: gh-pages
          publish_dir: ./homepage
          cname: ziyixi.science
          commit_message: ${{ github.event.head_commit.message }}
